In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Iris.csv to Iris.csv

In [3]:
import io

In [7]:
df = pd.read_csv(io.BytesIO(uploaded['Iris.csv']))
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
x = df.iloc[:,:4].values

In [8]:
y = df['Species'].values

In [10]:
df.head(5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [15]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
from sklearn.naive_bayes import GaussianNB 
classifier = GaussianNB()
classifier.fit(X_train, y_train)
GaussianNB()
y_pred = classifier.predict(X_test) 
y_pred

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor'],
      dtype='<U15')

In [24]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred}) 
df

        Real Values Predicted Values
0   Iris-versicolor  Iris-versicolor
1   Iris-versicolor  Iris-versicolor
2       Iris-setosa      Iris-setosa
3   Iris-versicolor  Iris-versicolor
4    Iris-virginica   Iris-virginica
5    Iris-virginica   Iris-virginica
6       Iris-setosa      Iris-setosa
7   Iris-versicolor  Iris-versicolor
8   Iris-versicolor  Iris-versicolor
9       Iris-setosa      Iris-setosa
10  Iris-versicolor  Iris-versicolor
11  Iris-versicolor  Iris-versicolor
12  Iris-versicolor  Iris-versicolor
13  Iris-versicolor  Iris-versicolor
14  Iris-versicolor  Iris-versicolor
15  Iris-versicolor  Iris-versicolor
16      Iris-setosa      Iris-setosa
17      Iris-setosa      Iris-setosa
18   Iris-virginica   Iris-virginica
19  Iris-versicolor  Iris-versicolor
20      Iris-setosa      Iris-setosa
21      Iris-setosa      Iris-setosa
22  Iris-versicolor  Iris-versicolor
23   Iris-virginica   Iris-virginica
24   Iris-virginica   Iris-virginica
25      Iris-setosa      Iris-setosa
26   Iris-virginica   Iris-virginica
27  Iris-versicolor  Iris-versicolor
28   Iris-virginica   Iris-virginica
29  Iris-versicolor  Iris-versicolor